### PR TITLE
Upgrades BuckleScript to 7.1.1 & fixes warnings

### PR DESCRIPTION
**Pull request by superherointj**
Please, accept. And publish it on NPM so I can get rid of BuckleScript warnings.

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks. What's the reason for upgrading the bs-platform devDependency to 7.1.1? Does it fix some other issue, and might that be considered a breaking change?

**Comment by superherointj** [comment]
When using 'bs-jest' in a BuckleScript 7.1.1 project BuckleScript would warn on "bs-jest" source code. So I just did enough to get rid of the warning messages. If it wasn't for this warning I wouldn't know about this issue. I don't think it is a breaking change because I don't know anything that broke because of this proposed change.

Also, there are still warnings of code 101: `Error (warning 101): Unused BuckleScript attribute: bs.uncurry`
Which I wasn't sure what it was supposed to do. So I did nothing.

And I did not include the compiled JS file because it is usually automatically generated. I was unsure about the project preference on this. I usually generate them automatically using CI.

**Comment by glennsl** [comment]
Thanks. I like to review the JS artifacts so I can check if upgrading causes any breaking changes. Doesn't look like there is any though.

I'll check the warnings. Might be that BuckleScript has gotten better at inferring them. I see from the JS artifacts that a few `Curry`. calls have been removed.

**Comment by glennsl** [comment]
I didn't get any warning when building cleanly, so I think it's good.

Released as 0.4.10

**Pull request merged**
