### PR TITLE
 Fix tests on bs-platform 4.0.7

### LINKED ISSUE #33: Doesn't work with bs-platform 4.0.7
I'm trying to upgrade to the latest bs-platform, but this breaks all of my Jest tests.

```
  ✕ renders (5025ms)

  ● renders

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

       7 | var ReactShallowRenderer = require("bs-react-test-renderer/src/ReactShallowRenderer.bs.js");
       8 |
    >  9 | Jest.test("renders", (function (param) {
         |      ^
      10 |         var component = ReactShallowRenderer.renderWithRenderer(ReasonReact.element(undefined, undefined, FourOhFour.make(/* array */[])));
      11 |         return Jest.Expect[/* toMatchSnapshot */16](Jest.Expect[/* expect */0](component));
      12 |       }));

      at Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
      at Object.test$1 [as test] (node_modules/@glennsl/bs-jest/src/jest.js:248:3)
      at Object.test (src/components/__tests__/fourOhFour_test.bs.js:9:6)
```

fourOhFour_test.re
```ocaml
open Jest;

open Expect;

test("renders", _ => {
  let component = <FourOhFour /> |> ReactShallowRenderer.renderWithRenderer;
  expect(Js.Undefined.return(component)) |> toMatchSnapshot;
});
```

fourOhFour.re
```ocaml
let component = ReasonReact.statelessComponent("404");

let make = _children => {...component, render: _self => <div> <h1> {ReasonReact.string("404")} </h1> </div>};
```

### PR DESCRIPTION
**Pull request by glennsl**
Modifies and closes #34, fixes #33

### CODE REVIEW

**Comment by glennsl** [comment]
@zploskey Can you verify that this still fixes the problem? Or is it enough that the tests here pass?

**Comment by glennsl** [comment]
It annoys me that the coverage is still lower, but it's my own fault for not tracking the js artifacts. I can't see anything obvious that would cause it though, so it's probably just that bsc's code generation got better and removed some unnecessary code.

I'll merge and release it after it's confirmed to fix the issue.

**Comment by zploskey** [comment]
The way to test this is to add bs-platform 4.0.7 as a dependency temporarily and then run the tests. They all passed with the initial version. I can't test it right away, unfortunately (on my phone).

**Comment by glennsl** [comment]
Ok, cool. I linked my global `bs-platform`, as I always do and which should accomplish the same, so I think it's good to go. This also shouldn't break backward compatibility, since as I understand it this just makes the old behavior explicit, so I'll just do a patch release.

Thanks @zploskey !

**Pull request merged**
